version: "3.2"
services:

  sql-server-db:
    container_name: article_database
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@55word"
      ACCEPT_EULA: "Y"
